[workspace]
resolver = "2"

members = [
  "core",
  "prob1",
  "prob2",
  "prob3",
  "prob4",
  "prob5",
  "prob6",
  "prob7",
  "prob8",
  "prob9",
  "prob10",
  "prob11",
  "prob12",
  "prob13",
  "prob14",
]
